[tool.poetry]
name = "halomodel-review"
version = "0.1.0"
description = ""
authors = ["Alexander Mead <alexander.j.mead@googlemail.com>"]
readme = "README.md"
packages = [{include = "halomodel_review"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
numpy = "^1.24.1"
matplotlib = "^3.6.2"
dark-emulator = "^1.0.23"
camb = "^1.3.6"
scipy = "^1.10.0"
ipykernel = "^6.19.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
